version: "3.3"
services:
    db:
        image: mysql:8.0.3
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_ROOT_HOST=%
            - default_authentication_plugin=mysql_native_password
            - LC_CTYPE=en_US.UTF-8
            - LC_ALL=en_US.UTF-8
        ports:
            - 3306:3306
        volumes:
            - ./mysql.conf:/etc/mysql/conf.d/custom.cnf
            - ./sql-data:/var/lib/mysql
        restart: always
        entrypoint: ['/entrypoint.sh', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
    pma:
        image: phpmyadmin/phpmyadmin
        environment:
            - MYSQL_ROOT_PASSWORD=
        ports:
            - 6969:80
        volumes:
            - /sessions
        restart: always
    web:
        image: funland:latest
        depends_on: [ "db" ]
        ports:
            - 8080:80
        volumes:
            - "./src:/var/www/html"
            - "./env.ini:/var/www/env.ini"
